name: atelyam
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_lints: ^2.0.1  # Adding a version for flutter_lints
  iconly: 
  flutter_svg:
  # cloud_firestore: ^4.6.0
  # firebase_messaging:
  cloud_firestore: ^2.2.1
  firebase_messaging: ^10.0.2
  lottie: ^3.1.0
  get_storage: ^2.0.0  # Added version for get_storage
  image_picker: ^0.8.5+3  # Added version for image_picker
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: 
  path_provider:
  animate_do: ^3.3.4
  font_awesome_flutter: 
  gal: ^2.3.1
  url_launcher:
  pull_to_refresh:
  photo_view:
  flutter_widget_from_html: ^0.15.3
  dio:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/image/flags/
    - assets/image/fasonlar/
    - assets/image/patterns/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
  uses-material-design: true
  generate: true