// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          'product_upload_success': 'Haryt üstünlikli ýüklendiňiz',
          'image_upload_failed': 'Surat ýüklenmedi täzeden synanşyň',
          'max_4_images': '4 sany surat ýükläp bilersiňiz',
          'product_deleted': 'Haryt pozuldy',
          'profil': 'Ulanyjy',
          'settings': 'Sazlamalar',
          'lang': 'Dil',
          'aboutUs': 'Biz Barada',
          'login': 'Giriş',
          'register': 'Agza bolmak',
          'logout': 'Çykmak',
          'log_out_title': 'Programmadan çykmak isleýärsiňizmi?',
          'yes': 'Hawwa',
          'no': 'Ýok',
          'business_accounts_profil': 'Biznes hasabym',
          'logOutUser': 'Siz üstünlikli ulgamdan çykdyňyz',
          'home': 'Baş sahypa',
          'categories': 'Kategoriýalar',
          'select_categories': 'Kategoriýalar görnüşini saýlaň',
          'favorites': 'Halanlarym',
          'more': 'Köpräk',
          'en': 'Iňlis',
          'tm': 'Türkmen',
          'tr': 'Türk',
          'ru': 'Rus',
          'ch': 'Hytaý',
          'all': 'Ählisi',
          'new': 'Täze',
          'popular': 'Meşhur',
          'banners_profile': 'Reklama',
          'types_of_business': 'Biznes görnüşleri',
          'select_types_of_business': 'Biznes görnüşleri saýläň',
          'commecial_users': 'Biznes ulanyjylary',
          'location': 'Salgy',
          'comingTitle': 'Ýakynda...',
          'comingSubtitle': 'Bu bölüm tiz wagtdan ulanyjylarymyz üçin elýeterli bolar. Sabyrly bolmagyňyzy haýyş edýäris.',
          'tab1': 'Maglumat',
          'tab2': 'Harytlar',
          'tab2Settings': 'Meniň harytlarym',
          'tab3': 'Wideolar',
          'phone_number': 'Telefon belgisi',
          'call': 'Jaň etmek',
          'info_product': 'Haryt barada',
          'sold': 'Satlyk',
          'most_popular_users': 'Iň meşhur ulanyjylar',
          'filter': 'Süzgüç',
          'count': 'haryt bar',
          'save_avatar': 'Awatary ýatda sakla',
          'choose_avatar': 'Awatar saýlaň',
          'name': 'Ulanyjy ady',
          'change_profile': 'Profiliňi üýtget',
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanş',
          'brandingTitle1': 'Atelyam: Stiliňizi görkeziň, başgalaryna ylham beriň',
          'brandingTitle2': 'El işi göz nuru dizaýnlaryňyzy dünýä görkeziň',
          'brandingTitle3': 'Gelinlikleriňiz we ýörite dizaýnlaryňyz bilen tapawutlanyň',
          'brandingTitle4': 'Öz elleriňiz bilen döreden modaňyzy paýlaşyň',
          'brandingTitle5': 'Atelýam: Her stiliň bir hekaýasy bar, Öz hekaýaňyzy gürrüň beriň',
          'brandingTitle6': 'Üýtgeşik dizaýnlaryňyz bilen moda dünýäsine ädim ädiň.',
          'brandingTitle7': 'Geýimleriňiz bilen däl, stiliňiz bilen öňe çykyň',
          'brandingTitle8': 'Atelýam: Modaňyzy sergilemek üçin iň dogry adres',
          'welcomeSubtitle': 'Ulanyjy adyňyzy we telefon belgiňizi dogry girizeniňize göz ýetiriň.',
          'code_has_been_sent_to': 'SMS kod şu belgä iberildi ',
          'verify': 'Tassykla',
          'verify_phone': 'Telefon belgisini tassyklaň',
          'error': 'Ýalňyşlyk',
          'errorOTP': 'Dogry OTP giriziň',
          'clear_all_favorites_desc': 'Halanlaryňyzdaky ähli önümleri pozmak isleýärsinizmi?',
          'clear_all_favorites': 'Ähli halanlarymy poz',
          'success': 'Üstünlikli',
          'successClearedFavorites': 'Ähli halanlaryňyz pozuldy.',
          'choose_language': 'Dil Saýlaň',
          'noFavoritesFound': 'Halanlaryňyza hiç haryt goşulmady.',
          'successOTP': 'Giriş üstünlikli boldy',
          'profile_change': 'Profil üýtgetmek',
          'change_profile_success': 'Ulanyjy profili üstünlikli üýtgedildi',
          'no_data_available': 'Maglumat ýok',
          'no_category_image': 'Surat ýok',
          'cancel': 'Ýatyr',
          'mostViewed': 'Iň köp görülen',
          'leastViewed': 'Iň az görülen',
          'lastAdded': 'Iň täze suratlar',
          'firstAdded': 'Iň köne suratlar',
          'mostViewedFasons': 'Iň köp görülen ',
          'add_product': 'Haryt goş',
          'create_business_account': 'Biznes hasaby döret',
          'create_product': 'Haryt döret',
          'networkError': 'Internet näsazlygy',
          'noInternet': 'Internet birikmesi ýok',
          'unknownError': 'Näbelli ýalňyşlyk',
          'anErrorOccurred': 'Ýalňyşlyk ýüze çykdy',
          'apiError': 'Internet näsazlygy',
          'invalidNumber': 'Nädogry Belgisi',
          'unauthorized': 'Rugsat berilmedik',
          'notFound': 'Tapylmady',
          'userDoesNotExist': 'Ulanyjy ýok, agza boluň',
          'userExistsLogin': 'Ulanyjy bar, giriň',
          'serverError': 'Internet näsazlygy',
          'last': 'Soňky goýulanlar',
          'first': 'Ilkinji goýulanlar',
          'viewcount': 'Iň köp Görülenler',
          'LowPrice': 'Arzandan Gymmada',
          'HighPrice': 'Gymmatdan Arzana',
          'sold': 'Satlyk',
          'info_product': 'Haryt Maglumatlary',
          'warning': 'Duýduryş',
          'storage_permission_denied': 'Ýatda saklama rugsat berilmedi. Ýüklemek amala aşyrylyp bilinmedi.',
          'downloading': 'Ýüklenýär',
          'download_started': 'Ýüklemek Başlady...',
          'success': 'Üstünlikli',
          'downloaded': 'Surat ýüklendi we Galereýa goşuldy.',
          'image_download_error': 'Surat ýüklenende ýalňyşlyk: ',
          'tab1': 'Maglumat',
          'tab2': 'Harytlar',
          'tab3': 'Wideolar',
          'comingTitle': 'Ýakynda',
          'comingSubtitle': 'Bu bölüm tiz wagtdan elýeterli bolar, täzeliklere garaşyň',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': 'Telefon belgisi',
          'location': 'Salgy',
          'url_error': 'URL açylyp bilinmedi',
          'url_error_message': 'Görmek isleýän URL-i açyp bilmedim',
          'productCount': 'haryt ',
          'business_accounts': 'Biznes hasaplary',
          'all_business_accounts': 'Ähli Biznes Hasaplary',
          'hashtag': 'Teg',
          'upload_image': 'Surat Ýükle',
          'product_name': 'Haryt Ady',
          'description': 'Düşündiriş',
          'price': 'Bahasy',
          'upload_product': 'Haryt Ýükle',
          'fill_all_fields': 'Ähli meýdançalary dolduryň',
          'product_uploaded_success': 'Haryt üstünlikli ýüklendi',
          'product_upload_failed': 'Haryt ýükläp bolmady:',
          'new_business_account': 'Täze Biznes Hasaby',
          'account_created': 'Biznes hasaby üstünlikli döredildi.',
          'phone_call_error': 'Jaň amala aşyrylyp bilinmedi: ',
          'new_product_upload': 'Täze Haryt Ýüklemek',
          'business_name': 'Biznes Ady',
          'phone': 'Telefon',
          'address': 'Salgy',
          'add_account': 'Hasap Goş',
          'logo_upload': 'Logo Ýükle',
          'account_created': 'Biznes hasaby üstünlikli döredildi.',
          'account_already_exist': 'Bu kategoriýada eýýäm biznes hasabyňyz bar.',
          'account_create_failed': 'Amal başa barmady: ',
          'sending_information': 'Maglumatyňyz serwere iberilýär, garaşyň...',
          'error': 'Ýalňyşlyk',
          'anErrorOccurred': 'Ýalňyşlyk ýüze çykdy: ',
          'update_business_account': 'Biznes Hasabyny Üýtgetmek',
          'update_product': 'Harydy üýtgetmek',
          'delete_product': 'Harydy Poz',
          'delete_account': 'Hasaby Poz',
          'update': 'Üýtget',
          'product_updated': 'Haryt üstünlikli üýtgedildi.',
          'product_not_updated': 'Harydy üýtgedip bolmady:',
          'delete': 'Poz',
          'are_you_sure': 'Bu biznes hasaby pozmak isleýärsiňizmi ?',
          'are_you_sure_product': 'Bu harydy pozmak isleýärsiňizmi ?',
          'product': 'haryt',
          'cancel': 'Ýok',
          'business_account_updated': 'Hasap üstünlikli üýtgedildi',
          'business_account_not_updated': 'Üýtgetmek başa barmady: ',
          'website': 'Websaýt',
          'deleted_success': 'Biznes hasabyňyz üstünlikli pozuldy',
          'wait': 'Garaşyň...',
          'wait_desc': 'Haýyşyňyzy işleýänçäk garaşyň',
          'inactive': 'Işlemeýär',
          'inactive_desc': 'Hasabyňyz işlemeýär. Goşmaça maglumat üçin goldaw bilen habarlaşyň.',
          'main_image_upload': 'Harydyň baş suratyny ýükle',
          'update_image': 'Harydyň suratyny üýtget',
          'product_updated': 'Haryt üstünlikli üýtgedildi',
          'update_failed': 'Üýtgetmek başa barmady',
          'pending': 'Garaşylýar',
          'active': 'Aktiw',
          'product_status': 'Haryt ýagdaýy',
          'upload_images': 'Harydyň suratlaryny ýükle',
          'add_image': 'Surat goş',
        },
        'tr': {
          'product_upload_success': 'Ürün başarıyla yüklendi',
          'image_upload_failed': 'Resim yüklenemedi, lütfen tekrar deneyiniz',
          'max_4_images': 'En fazla 4 resim yükleyebilirsiniz',
          'product_deleted': 'Ürün silindi',
          'profil': 'Profil',
          'settings': 'Ayarlar',
          'lang': 'Dil',
          'aboutUs': 'Hakkımızda',
          'login': 'Giriş Yap',
          'register': 'Kayıt Ol',
          'logout': 'Çıkış Yap',
          'log_out_title': 'Uygulamadan çıkmak istediğinize emin misiniz?',
          'yes': 'Evet',
          'no': 'Hayır',
          'business_accounts_profil': 'İşletme Hesabım',
          'logOutUser': 'Başarıyla çıkış yaptınız',
          'home': 'Ana Sayfa',
          'categories': 'Kategoriler',
          'select_categories': 'Kategori seçin',
          'favorites': 'Favorilerim',
          'more': 'Daha Fazla',
          'en': 'İngilizce',
          'tm': 'Türkmence',
          'tr': 'Türkçe',
          'ru': 'Rusça',
          'ch': 'Çince',
          'all': 'Tümü',
          'new': 'Yeni',
          'popular': 'Popüler',
          'banners_profile': 'Reklamlar',
          'types_of_business': 'İşletme Türleri',
          'select_types_of_business': 'İşletme türünü seçin',
          'commecial_users': 'İşletme Kullanıcıları',
          'location': 'Konum',
          'comingTitle': 'Çok Yakında...',
          'comingSubtitle': 'Bu bölüm çok yakında kullanıcılarımız için erişilebilir olacak. Sabrınız için teşekkür ederiz.',
          'tab1': 'Bilgi',
          'tab2': 'Ürünler',
          'tab2Settings': 'Ürünlerim',
          'tab3': 'Videolar',
          'phone_number': 'Telefon Numarası',
          'call': 'Ara',
          'info_product': 'Ürün Hakkında',
          'sold': 'Satılık',
          'most_popular_users': 'En Popüler Kullanıcılar',
          'filter': 'Filtre',
          'count': 'ürün var',
          'save_avatar': 'Avatarı Kaydet',
          'choose_avatar': 'Avatar Seçin',
          'name': 'Kullanıcı Adı',
          'change_profile': 'Profili Değiştir',
          'noConnection1': 'Bağlantı Yok',
          'noConnection2': 'İnternete bağlanılamadı. Lütfen internet ayarlarınızı kontrol edip tekrar deneyin!',
          'noConnection3': 'Tekrar Dene',
          'brandingTitle1': 'Atölyem: Tarzınızı Gösterin, Başkalarına İlham Verin',
          'brandingTitle2': 'El Emeği Göz Nuru Tasarımlarınızı Dünyaya Gösterin',
          'brandingTitle3': 'Gelinlikleriniz ve Özel Tasarımlarınızla Fark Yaratın',
          'brandingTitle4': 'Kendi Ellerinizle Yarattığınız Modayı Paylaşın',
          'brandingTitle5': 'Atölyem: Her Tarzın Bir Hikayesi Var, Kendi Hikayenizi Anlatın',
          'brandingTitle6': 'Özgün Tasarımlarınızla Moda Dünyasına Adım Atın.',
          'brandingTitle7': 'Kıyafetlerinizle Değil, Tarzınızla Öne Çıkın',
          'brandingTitle8': 'Atölyem: Modanızı Sergilemek İçin En Doğru Adres',
          'welcomeSubtitle': 'Kullanıcı adınızı ve telefon numaranızı doğru girdiğinizden emin olun.',
          'code_has_been_sent_to': 'SMS kodu şu numaraya gönderildi ',
          'verify': 'Doğrula',
          'verify_phone': 'Telefon numaranızı doğrulayın',
          'error': 'Hata',
          'errorOTP': 'Geçerli bir OTP girin',
          'clear_all_favorites_desc': 'Favorilerinizdeki tüm ürünleri silmek istediğinize emin misiniz?',
          'clear_all_favorites': 'Tüm Favorileri Temizle',
          'success': 'Başarılı',
          'successClearedFavorites': 'Tüm favorileriniz temizlendi.',
          'choose_language': 'Dil Seçin',
          'noFavoritesFound': 'Favorilerinize henüz ürün eklenmedi.',
          'successOTP': 'Giriş başarılı',
          'profile_change': 'Profil Güncelleme',
          'change_profile_success': 'Kullanıcı profili başarıyla güncellendi',
          'no_data_available': 'Veri bulunamadı',
          'no_category_image': 'Resim yok',
          'cancel': 'İptal',
          'mostViewed': 'En Çok Görüntülenenler',
          'leastViewed': 'En Az Görüntülenenler',
          'lastAdded': 'En Yeni Eklenenler',
          'firstAdded': 'En Eski Eklenenler',
          'mostViewedFasons': 'En Çok Görüntülenenler ',
          'add_product': 'Ürün Ekle',
          'create_business_account': 'İşletme Hesabı Oluştur',
          'create_product': 'Ürün Oluştur',
          'networkError': 'Ağ Hatası',
          'noInternet': 'İnternet Bağlantısı Yok',
          'unknownError': 'Bilinmeyen Hata',
          'anErrorOccurred': 'Bir Hata Oluştu',
          'apiError': 'Ağ hatası',
          'invalidNumber': 'Geçersiz Numara',
          'unauthorized': 'Yetkisiz',
          'notFound': 'Bulunamadı',
          'userDoesNotExist': 'Kullanıcı yok, kayıt olun',
          'userExistsLogin': 'Kullanıcı var, giriş yapın',
          'serverError': 'Ağ Hatası',
          'last': 'Son Eklenenler',
          'first': 'İlk Eklenenler',
          'viewcount': 'En Çok Görüntülenenler',
          'LowPrice': 'Düşük Fiyattan Yükseğe',
          'HighPrice': 'Yüksek Fiyattan Düşüğe',
          'sold': 'Satılık',
          'info_product': 'Ürün Bilgileri',
          'warning': 'Uyarı',
          'storage_permission_denied': 'Depolama izni verilmedi. İndirme yapılamadı.',
          'downloading': 'İndiriliyor',
          'download_started': 'İndirme Başladı...',
          'success': 'Başarılı',
          'downloaded': 'Resim indirildi ve Galeriye eklendi.',
          'image_download_error': 'Resim indirilirken hata oluştu: ',
          'tab1': 'Bilgi',
          'tab2': 'Ürünler',
          'tab3': 'Videolar',
          'comingTitle': 'Çok Yakında',
          'comingSubtitle': 'Bu bölüm çok yakında kullanıma açılacaktır, güncellemeleri takipte kalın',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': 'Telefon numarası',
          'location': 'Konum',
          'url_error': 'URL açılamadı',
          'url_error_message': "Görüntülemek istediğim URL'i açamadım",
          'productCount': 'ürün',
          'business_accounts': 'İşletme Hesapları',
          'all_business_accounts': 'Tüm İşletme Hesapları',
          'hashtag': 'Etiket',
          'upload_image': 'Resim Yükle',
          'product_name': 'Ürün Adı',
          'description': 'Açıklama',
          'price': 'Fiyatı',
          'upload_product': 'Ürün Yükle',
          'fill_all_fields': 'Tüm alanları doldurun',
          'product_uploaded_success': 'Ürün başarıyla yüklendi',
          'product_upload_failed': 'Ürün yüklenemedi:',
          'new_business_account': 'Yeni İşletme Hesabı',
          'account_created': 'İşletme hesabı başarıyla oluşturuldu.',
          'phone_call_error': 'Arama gerçekleştirilemedi: ',
          'new_product_upload': 'Yeni Ürün Yükle',
          'business_name': 'İşletme Adı',
          'phone': 'Telefon',
          'address': 'Adres',
          'add_account': 'Hesap Ekle',
          'logo_upload': 'Logo Yükle',
          'account_created': 'İşletme hesabı başarıyla oluşturuldu.',
          'account_already_exist': 'Bu kategoride zaten bir işletme hesabınız var.',
          'account_create_failed': 'İşlem başarısız oldu: ',
          'sending_information': 'Bilgileriniz sunucuya gönderiliyor, lütfen bekleyin...',
          'error': 'Hata',
          'anErrorOccurred': 'Bir hata oluştu: ',
          'update_business_account': 'İşletme Hesabını Güncelle',
          'update_product': 'Ürünü Güncelle',
          'delete_product': 'Ürünü Sil',
          'delete_account': 'Hesabı Sil',
          'update': 'Güncelle',
          'product_updated': 'Ürün başarıyla güncellendi.',
          'product_not_updated': 'Ürün güncellenemedi:',
          'delete': 'Sil',
          'are_you_sure': 'Bu işletme hesabını silmek istediğinize emin misiniz?',
          'are_you_sure_product': 'Bu ürünü silmek istediğinize emin misiniz?',
          'product': 'ürün',
          'cancel': 'Hayır',
          'business_account_updated': 'Hesap başarıyla güncellendi',
          'business_account_not_updated': 'Güncelleme başarısız oldu: ',
          'website': 'Web sitesi',
          'deleted_success': 'İşletme hesabınız başarıyla silindi',
          'wait': 'Bekleyin...',
          'wait_desc': 'İsteğiniz işlenene kadar bekleyin',
          'inactive': 'Aktif Değil',
          'inactive_desc': 'Hesabınız aktif değil. Ek bilgi için destek ile iletişime geçin.',
          'main_image_upload': 'Ürünün ana resmini yükle',
          'update_image': 'Ürünün resmini değiştir',
          'product_updated': 'Ürün başarıyla güncellendi',
          'update_failed': 'Güncelleme başarısız oldu',
          'pending': 'Bekliyor',
          'active': 'Aktif',
          'product_status': 'Ürün durumu',
          'upload_images': 'Ürünün resimlerini yükle',
          'add_image': 'Resim ekle',
        },
        'ru': {
          'product_upload_success': 'Товар успешно загружен',
          'image_upload_failed': 'Не удалось загрузить изображение, попробуйте еще раз',
          'max_4_images': 'Вы можете загрузить не более 4 изображений',
          'product_deleted': 'Товар удален',
          'profil': 'Профиль',
          'settings': 'Настройки',
          'lang': 'Язык',
          'aboutUs': 'О нас',
          'login': 'Войти',
          'register': 'Зарегистрироваться',
          'logout': 'Выйти',
          'log_out_title': 'Вы уверены, что хотите выйти из приложения?',
          'yes': 'Да',
          'no': 'Нет',
          'business_accounts_profil': 'Мой бизнес-аккаунт',
          'logOutUser': 'Вы успешно вышли из системы',
          'home': 'Главная',
          'categories': 'Категории',
          'select_categories': 'Выберите категорию',
          'favorites': 'Избранное',
          'more': 'Больше',
          'en': 'Английский',
          'tm': 'Туркменский',
          'tr': 'Турецкий',
          'ru': 'Русский',
          'ch': 'Китайский',
          'all': 'Все',
          'new': 'Новое',
          'popular': 'Популярное',
          'banners_profile': 'Реклама',
          'types_of_business': 'Виды бизнеса',
          'select_types_of_business': 'Выберите вид бизнеса',
          'commecial_users': 'Бизнес пользователи',
          'location': 'Адрес',
          'comingTitle': 'Скоро...',
          'comingSubtitle': 'Этот раздел скоро будет доступен для наших пользователей. Пожалуйста, наберитесь терпения.',
          'tab1': 'Информация',
          'tab2': 'Товары',
          'tab2Settings': 'Мои товары',
          'tab3': 'Видео',
          'phone_number': 'Номер телефона',
          'call': 'Позвонить',
          'info_product': 'О товаре',
          'sold': 'Продается',
          'most_popular_users': 'Самые популярные пользователи',
          'filter': 'Фильтр',
          'count': 'товаров',
          'save_avatar': 'Сохранить аватар',
          'choose_avatar': 'Выберите аватар',
          'name': 'Имя пользователя',
          'change_profile': 'Изменить профиль',
          'noConnection1': 'Нет соединения',
          'noConnection2': 'Не удалось подключиться к Интернету. Пожалуйста, проверьте настройки интернета и попробуйте снова!',
          'noConnection3': 'Попробовать снова',
          'brandingTitle1': 'Ателье: Покажите свой стиль, вдохновите других',
          'brandingTitle2': 'Покажите миру свои творения ручной работы',
          'brandingTitle3': 'Выделяйтесь своими свадебными и специальными дизайнами',
          'brandingTitle4': 'Делитесь модой, которую вы создаете своими руками',
          'brandingTitle5': 'Ателье: У каждого стиля есть своя история, расскажите свою',
          'brandingTitle6': 'Сделайте шаг в мир моды с вашими уникальными дизайнами.',
          'brandingTitle7': 'Выделяйтесь не одеждой, а стилем',
          'brandingTitle8': 'Ателье: Самый правильный адрес для демонстрации вашей моды',
          'welcomeSubtitle': 'Убедитесь, что вы правильно ввели свое имя пользователя и номер телефона.',
          'code_has_been_sent_to': 'СМС код был отправлен на этот номер ',
          'verify': 'Подтвердить',
          'verify_phone': 'Подтвердите номер телефона',
          'error': 'Ошибка',
          'errorOTP': 'Введите правильный OTP',
          'clear_all_favorites_desc': 'Вы уверены, что хотите удалить все товары из избранного?',
          'clear_all_favorites': 'Очистить все избранные',
          'success': 'Успешно',
          'successClearedFavorites': 'Все ваши избранные были очищены.',
          'choose_language': 'Выберите язык',
          'noFavoritesFound': 'В избранное не добавлено ни одного товара.',
          'successOTP': 'Вход выполнен успешно',
          'profile_change': 'Изменение профиля',
          'change_profile_success': 'Профиль пользователя успешно изменен',
          'no_data_available': 'Нет доступных данных',
          'no_category_image': 'Нет изображения',
          'cancel': 'Отмена',
          'mostViewed': 'Самые просматриваемые',
          'leastViewed': 'Наименее просматриваемые',
          'lastAdded': 'Последние добавленные',
          'firstAdded': 'Первые добавленные',
          'mostViewedFasons': 'Самые просматриваемые ',
          'add_product': 'Добавить товар',
          'create_business_account': 'Создать бизнес-аккаунт',
          'create_product': 'Создать товар',
          'networkError': 'Сетевая ошибка',
          'noInternet': 'Нет подключения к интернету',
          'unknownError': 'Неизвестная ошибка',
          'anErrorOccurred': 'Произошла ошибка',
          'apiError': 'Сетевая ошибка',
          'invalidNumber': 'Неверный номер',
          'unauthorized': 'Не авторизован',
          'notFound': 'Не найдено',
          'userDoesNotExist': 'Пользователя не существует, зарегистрируйтесь',
          'userExistsLogin': 'Пользователь существует, войдите',
          'serverError': 'Сетевая ошибка',
          'last': 'Последние',
          'first': 'Первые',
          'viewcount': 'Самые просматриваемые',
          'LowPrice': 'От низкой цены к высокой',
          'HighPrice': 'От высокой цены к низкой',
          'sold': 'Продается',
          'info_product': 'Информация о товаре',
          'warning': 'Предупреждение',
          'storage_permission_denied': 'Разрешение на хранение не предоставлено. Загрузка не выполнена.',
          'downloading': 'Загрузка',
          'download_started': 'Загрузка началась...',
          'success': 'Успешно',
          'downloaded': 'Изображение загружено и добавлено в Галерею.',
          'image_download_error': 'Ошибка при загрузке изображения: ',
          'tab1': 'Информация',
          'tab2': 'Товары',
          'tab3': 'Видео',
          'comingTitle': 'Скоро',
          'comingSubtitle': 'Этот раздел скоро будет доступен, следите за обновлениями',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': 'Номер телефона',
          'location': 'Адрес',
          'url_error': 'Не удалось открыть URL',
          'url_error_message': 'Не удалось открыть URL, который вы хотели просмотреть',
          'productCount': 'товаров',
          'business_accounts': 'Бизнес аккаунты',
          'all_business_accounts': 'Все бизнес аккаунты',
          'hashtag': 'Хэштег',
          'upload_image': 'Загрузить изображение',
          'product_name': 'Название товара',
          'description': 'Описание',
          'price': 'Цена',
          'upload_product': 'Загрузить товар',
          'fill_all_fields': 'Заполните все поля',
          'product_uploaded_success': 'Товар успешно загружен',
          'product_upload_failed': 'Не удалось загрузить товар:',
          'new_business_account': 'Новый бизнес аккаунт',
          'account_created': 'Бизнес-аккаунт успешно создан.',
          'phone_call_error': 'Не удалось совершить звонок: ',
          'new_product_upload': 'Загрузить новый товар',
          'business_name': 'Название бизнеса',
          'phone': 'Телефон',
          'address': 'Адрес',
          'add_account': 'Добавить аккаунт',
          'logo_upload': 'Загрузить логотип',
          'account_created': 'Бизнес-аккаунт успешно создан.',
          'account_already_exist': 'У вас уже есть бизнес-аккаунт в этой категории.',
          'account_create_failed': 'Операция не удалась: ',
          'sending_information': 'Ваша информация отправляется на сервер, пожалуйста, подождите...',
          'error': 'Ошибка',
          'anErrorOccurred': 'Произошла ошибка: ',
          'update_business_account': 'Обновить бизнес-аккаунт',
          'update_product': 'Обновить товар',
          'delete_product': 'Удалить товар',
          'delete_account': 'Удалить аккаунт',
          'update': 'Обновить',
          'product_updated': 'Товар успешно обновлен.',
          'product_not_updated': 'Не удалось обновить товар:',
          'delete': 'Удалить',
          'are_you_sure': 'Вы уверены, что хотите удалить этот бизнес-аккаунт?',
          'are_you_sure_product': 'Вы уверены, что хотите удалить этот товар?',
          'product': 'товар',
          'cancel': 'Нет',
          'business_account_updated': 'Аккаунт успешно обновлен',
          'business_account_not_updated': 'Обновление не удалось: ',
          'website': 'Веб-сайт',
          'deleted_success': 'Ваш бизнес-аккаунт успешно удален',
          'wait': 'Подождите...',
          'wait_desc': 'Пожалуйста, подождите пока ваш запрос обрабатывается',
          'inactive': 'Неактивно',
          'inactive_desc': 'Ваш аккаунт неактивен. Для дополнительной информации свяжитесь со службой поддержки.',
          'main_image_upload': 'Загрузите главное изображение товара',
          'update_image': 'Изменить изображение товара',
          'product_updated': 'Товар успешно обновлен',
          'update_failed': 'Обновление не удалось',
          'pending': 'В ожидании',
          'active': 'Активно',
          'product_status': 'Статус товара',
          'upload_images': 'Загрузите изображения товара',
          'add_image': 'Добавить изображение',
        },
        'en': {
          'product_upload_success': 'Product uploaded successfully',
          'image_upload_failed': 'Image upload failed, please try again',
          'max_4_images': 'You can upload a maximum of 4 images',
          'product_deleted': 'Product deleted',
          'profil': 'Profile',
          'settings': 'Settings',
          'lang': 'Language',
          'aboutUs': 'About Us',
          'login': 'Login',
          'register': 'Register',
          'logout': 'Logout',
          'log_out_title': 'Are you sure you want to log out?',
          'yes': 'Yes',
          'no': 'No',
          'business_accounts_profil': 'My Business Account',
          'logOutUser': 'You have successfully logged out',
          'home': 'Home',
          'categories': 'Categories',
          'select_categories': 'Select Categories',
          'favorites': 'Favorites',
          'more': 'More',
          'en': 'English',
          'tm': 'Turkmen',
          'tr': 'Turkish',
          'ru': 'Russian',
          'ch': 'Chinese',
          'all': 'All',
          'new': 'New',
          'popular': 'Popular',
          'banners_profile': 'Banners',
          'types_of_business': 'Types of Business',
          'select_types_of_business': 'Select Types of Business',
          'commecial_users': 'Business Users',
          'location': 'Location',
          'comingTitle': 'Coming Soon...',
          'comingSubtitle': 'This section will be available for our users soon. Please be patient.',
          'tab1': 'Information',
          'tab2': 'Products',
          'tab2Settings': 'My Products',
          'tab3': 'Videos',
          'phone_number': 'Phone Number',
          'call': 'Call',
          'info_product': 'About Product',
          'sold': 'For Sale',
          'most_popular_users': 'Most Popular Users',
          'filter': 'Filter',
          'count': 'products',
          'save_avatar': 'Save Avatar',
          'choose_avatar': 'Choose Avatar',
          'name': 'Username',
          'change_profile': 'Change Profile',
          'noConnection1': 'No Connection',
          'noConnection2': 'Could not connect to the internet. Please check your internet settings and try again!',
          'noConnection3': 'Try Again',
          'brandingTitle1': 'Atelyam: Show Your Style, Inspire Others',
          'brandingTitle2': 'Show the World Your Handmade Designs',
          'brandingTitle3': 'Stand Out with Your Wedding Dresses and Special Designs',
          'brandingTitle4': 'Share the Fashion You Create with Your Own Hands',
          'brandingTitle5': 'Atelyam: Every Style Has a Story, Tell Your Story',
          'brandingTitle6': 'Take a Step into the World of Fashion with Your Unique Designs.',
          'brandingTitle7': 'Stand Out Not With Your Clothes, But With Your Style',
          'brandingTitle8': 'Atelyam: The Right Place to Showcase Your Fashion',
          'welcomeSubtitle': 'Make sure you have entered your username and phone number correctly.',
          'code_has_been_sent_to': 'An SMS code has been sent to this number ',
          'verify': 'Verify',
          'verify_phone': 'Verify Phone Number',
          'error': 'Error',
          'errorOTP': 'Enter a valid OTP',
          'clear_all_favorites_desc': 'Are you sure you want to clear all items from your favorites?',
          'clear_all_favorites': 'Clear All Favorites',
          'success': 'Success',
          'successClearedFavorites': 'All your favorites have been cleared.',
          'choose_language': 'Choose Language',
          'noFavoritesFound': 'No items have been added to your favorites yet.',
          'successOTP': 'Login Successful',
          'profile_change': 'Profile Change',
          'change_profile_success': 'User profile updated successfully',
          'no_data_available': 'No data available',
          'no_category_image': 'No image',
          'cancel': 'Cancel',
          'mostViewed': 'Most Viewed',
          'leastViewed': 'Least Viewed',
          'lastAdded': 'Last Added',
          'firstAdded': 'First Added',
          'mostViewedFasons': 'Most Viewed ',
          'add_product': 'Add Product',
          'create_business_account': 'Create Business Account',
          'create_product': 'Create Product',
          'networkError': 'Network Error',
          'noInternet': 'No Internet Connection',
          'unknownError': 'Unknown Error',
          'anErrorOccurred': 'An Error Occurred',
          'apiError': 'Api Error',
          'invalidNumber': 'Invalid Number',
          'unauthorized': 'Unauthorized',
          'notFound': 'Not Found',
          'userDoesNotExist': 'User does not exist, register',
          'userExistsLogin': 'User exists, login',
          'serverError': 'Server Error',
          'last': 'Last Added',
          'first': 'First Added',
          'viewcount': 'Most Viewed',
          'LowPrice': 'Low to High Price',
          'HighPrice': 'High to Low Price',
          'sold': 'For Sale',
          'info_product': 'Product Information',
          'warning': 'Warning',
          'storage_permission_denied': 'Storage permission was denied. Download could not be completed.',
          'downloading': 'Downloading',
          'download_started': 'Download Started...',
          'success': 'Success',
          'downloaded': 'Image downloaded and added to Gallery.',
          'image_download_error': 'Error while downloading image: ',
          'tab1': 'Information',
          'tab2': 'Products',
          'tab3': 'Videos',
          'comingTitle': 'Coming Soon',
          'comingSubtitle': 'This section will be available soon, stay tuned for updates',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': 'Phone number',
          'location': 'Location',
          'url_error': 'URL could not be opened',
          'url_error_message': 'Could not open the URL you wanted to view',
          'productCount': 'products',
          'business_accounts': 'Business Accounts',
          'all_business_accounts': 'All Business Accounts',
          'hashtag': 'Hashtag',
          'upload_image': 'Upload Image',
          'product_name': 'Product Name',
          'description': 'Description',
          'price': 'Price',
          'upload_product': 'Upload Product',
          'fill_all_fields': 'Fill all fields',
          'product_uploaded_success': 'Product uploaded successfully',
          'product_upload_failed': 'Product upload failed:',
          'new_business_account': 'New Business Account',
          'account_created': 'Business account created successfully.',
          'phone_call_error': 'Call could not be made: ',
          'new_product_upload': 'Upload New Product',
          'business_name': 'Business Name',
          'phone': 'Phone',
          'address': 'Address',
          'add_account': 'Add Account',
          'logo_upload': 'Upload Logo',
          'account_created': 'Business account created successfully.',
          'account_already_exist': 'You already have a business account in this category.',
          'account_create_failed': 'Operation failed: ',
          'sending_information': 'Your information is being sent to the server, please wait...',
          'error': 'Error',
          'anErrorOccurred': 'An error occurred: ',
          'update_business_account': 'Update Business Account',
          'update_product': 'Update Product',
          'delete_product': 'Delete Product',
          'delete_account': 'Delete Account',
          'update': 'Update',
          'product_updated': 'Product updated successfully.',
          'product_not_updated': 'Product could not be updated:',
          'delete': 'Delete',
          'are_you_sure': 'Are you sure you want to delete this business account?',
          'are_you_sure_product': 'Are you sure you want to delete this product?',
          'product': 'product',
          'cancel': 'No',
          'business_account_updated': 'Account updated successfully',
          'business_account_not_updated': 'Update failed: ',
          'website': 'Website',
          'deleted_success': 'Your business account has been successfully deleted',
          'wait': 'Wait...',
          'wait_desc': 'Please wait while your request is being processed',
          'inactive': 'Inactive',
          'inactive_desc': 'Your account is inactive. Contact support for more information.',
          'main_image_upload': 'Upload main image of the product',
          'update_image': "Change product's image",
          'product_updated': 'Product updated successfully',
          'update_failed': 'Update failed',
          'pending': 'Pending',
          'active': 'Active',
          'product_status': 'Product Status',
          'upload_images': 'Upload product images',
          'add_image': 'Add image',
        },
        'ch': {
          'product_upload_success': '商品上传成功',
          'image_upload_failed': '图片上传失败，请重试',
          'max_4_images': '您最多可以上传 4 张图片',
          'product_deleted': '商品已删除',
          'profil': '个人资料',
          'settings': '设置',
          'lang': '语言',
          'aboutUs': '关于我们',
          'login': '登录',
          'register': '注册',
          'logout': '登出',
          'log_out_title': '您确定要退出应用程序吗？',
          'yes': '是',
          'no': '否',
          'business_accounts_profil': '我的商家账户',
          'logOutUser': '您已成功登出',
          'home': '主页',
          'categories': '类别',
          'select_categories': '选择类别',
          'favorites': '收藏夹',
          'more': '更多',
          'en': '英语',
          'tm': '土库曼语',
          'tr': '土耳其语',
          'ru': '俄语',
          'ch': '中文',
          'all': '全部',
          'new': '新的',
          'popular': '热门',
          'banners_profile': '广告',
          'types_of_business': '商家类型',
          'select_types_of_business': '选择商家类型',
          'commecial_users': '商业用户',
          'location': '位置',
          'comingTitle': '即将推出...',
          'comingSubtitle': '此部分将很快对我们的用户开放。请耐心等待。',
          'tab1': '信息',
          'tab2': '产品',
          'tab2Settings': '我的产品',
          'tab3': '视频',
          'phone_number': '电话号码',
          'call': '呼叫',
          'info_product': '关于产品',
          'sold': '出售中',
          'most_popular_users': '最受欢迎的用户',
          'filter': '筛选',
          'count': '件商品',
          'save_avatar': '保存头像',
          'choose_avatar': '选择头像',
          'name': '用户名',
          'change_profile': '更改个人资料',
          'noConnection1': '无连接',
          'noConnection2': '无法连接到互联网。请检查您的互联网设置并重试！',
          'noConnection3': '重试',
          'brandingTitle1': 'Atelyam：展示您的风格，启发他人',
          'brandingTitle2': '向世界展示您的手工设计',
          'brandingTitle3': '以您的婚纱和特殊设计脱颖而出',
          'brandingTitle4': '分享您亲手创造的时尚',
          'brandingTitle5': 'Atelyam：每种风格都有一个故事，讲述您的故事',
          'brandingTitle6': '以您独特的设计迈入时尚界。',
          'brandingTitle7': '不要以衣服，而是以风格脱颖而出',
          'brandingTitle8': 'Atelyam：展示您时尚的最佳去处',
          'welcomeSubtitle': '请确保您已正确输入用户名和电话号码。',
          'code_has_been_sent_to': '短信验证码已发送至此号码 ',
          'verify': '验证',
          'verify_phone': '验证电话号码',
          'error': '错误',
          'errorOTP': '请输入有效的OTP',
          'clear_all_favorites_desc': '您确定要清除收藏夹中的所有商品吗？',
          'clear_all_favorites': '清除所有收藏夹',
          'success': '成功',
          'successClearedFavorites': '您的所有收藏夹已清除。',
          'choose_language': '选择语言',
          'noFavoritesFound': '您的收藏夹中尚未添加任何商品。',
          'successOTP': '登录成功',
          'profile_change': '个人资料更改',
          'change_profile_success': '用户资料已成功更新',
          'no_data_available': '没有可用数据',
          'no_category_image': '没有图片',
          'cancel': '取消',
          'mostViewed': '最多浏览',
          'leastViewed': '最少浏览',
          'lastAdded': '最新添加',
          'firstAdded': '最早添加',
          'mostViewedFasons': '最多浏览 ',
          'add_product': '添加商品',
          'create_business_account': '创建商家账户',
          'create_product': '创建商品',
          'networkError': '网络错误',
          'noInternet': '无网络连接',
          'unknownError': '未知错误',
          'anErrorOccurred': '发生错误',
          'apiError': '网络错误',
          'invalidNumber': '无效号码',
          'unauthorized': '未授权',
          'notFound': '未找到',
          'userDoesNotExist': '用户不存在，请注册',
          'userExistsLogin': '用户存在，请登录',
          'serverError': '服务器错误',
          'last': '最新添加',
          'first': '最早添加',
          'viewcount': '最多浏览',
          'LowPrice': '价格从低到高',
          'HighPrice': '价格从高到低',
          'sold': '出售中',
          'info_product': '产品信息',
          'warning': '警告',
          'storage_permission_denied': '存储权限被拒绝。无法完成下载。',
          'downloading': '正在下载',
          'download_started': '下载开始...',
          'success': '成功',
          'downloaded': '图片已下载并添加到图库。',
          'image_download_error': '下载图片时出错：',
          'tab1': '信息',
          'tab2': '产品',
          'tab3': '视频',
          'comingTitle': '即将推出',
          'comingSubtitle': '此部分即将推出，请关注更新',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': '电话号码',
          'location': '位置',
          'url_error': '无法打开URL',
          'url_error_message': '无法打开您想查看的URL',
          'productCount': '件商品',
          'business_accounts': '商家账户',
          'all_business_accounts': '所有商家账户',
          'hashtag': '标签',
          'upload_image': '上传图片',
          'product_name': '产品名称',
          'description': '描述',
          'price': '价格',
          'upload_product': '上传产品',
          'fill_all_fields': '填写所有字段',
          'product_uploaded_success': '产品上传成功',
          'product_upload_failed': '产品上传失败：',
          'new_business_account': '新的商家账户',
          'account_created': '商家账户创建成功。',
          'phone_call_error': '无法进行通话：',
          'new_product_upload': '上传新产品',
          'business_name': '商家名称',
          'phone': '电话',
          'address': '地址',
          'add_account': '添加账户',
          'logo_upload': '上传Logo',
          'account_created': '商家账户创建成功。',
          'account_already_exist': '您已在此类别中拥有一个商家账户。',
          'account_create_failed': '操作失败：',
          'sending_information': '您的信息正在发送到服务器，请稍候...',
          'error': '错误',
          'anErrorOccurred': '发生错误：',
          'update_business_account': '更新商家账户',
          'update_product': '更新产品',
          'delete_product': '删除产品',
          'delete_account': '删除账户',
          'update': '更新',
          'product_updated': '产品已成功更新。',
          'product_not_updated': '无法更新产品：',
          'delete': '删除',
          'are_you_sure': '您确定要删除此商家账户吗？',
          'are_you_sure_product': '您确定要删除此产品吗？',
          'product': '产品',
          'cancel': '否',
          'business_account_updated': '账户已成功更新',
          'business_account_not_updated': '更新失败：',
          'website': '网站',
          'deleted_success': '您的商家账户已成功删除',
          'wait': '请稍候...',
          'wait_desc': '请等待您的请求处理完毕',
          'inactive': '不活跃',
          'inactive_desc': '您的账户不活跃。请联系支持部门获取更多信息。',
          'main_image_upload': '上传产品的主图',
          'update_image': '更改产品图片',
          'product_updated': '产品已成功更新',
          'update_failed': '更新失败',
          'pending': '待定',
          'active': '活跃',
          'product_status': '产品状态',
          'upload_images': '上传产品图片',
          'add_image': '添加图片',
        },
      };
}
