// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'profil': 'Profile',
          'settings': 'Settings',
          'lang': 'Language',
          'aboutUs': 'About Us',
          'login': 'Login',
          'register': 'Register',
          'logout': 'Logout',
          'log_out_title': 'Do you want to really quit Our App?',
          'yes': 'Yes',
          'no': 'No',
          'logOutUser': 'You are logged out app successfully :(',
          'home': 'Home',
          'search': 'Search',
          'categories': 'Categories',
          'favorites': 'Favorites',
          'cart': 'Cart',
          'more': 'More',
          'dark': 'Dark',
          'light': 'Light',
          'en': 'English',
          'tm': 'Turkmen',
          'tr': 'Turkish',
          'ru': 'Russian',
          'ch': 'Chinese',
          'fashion': 'Fashion',
          'summer': 'Summer',
          'winter': 'Winter',
          'spring': 'Spring',
          'autumn': 'Autumn',
          'all': 'All',
          'new': 'New',
          'popular': 'Popular',
          'banners_profile': 'Banner Profile',
          'types_of_business': 'Types of Businesses',
          'commecial_users': 'Commercial Users',
          'location': 'Address',
          'comingTitle': 'Soon....',
          'comingSubtitle': 'This section will be available to our users very soon. We kindly ask for your patience.',
          'tab1': 'Information',
          'tab2': 'Products',
          'tab2Settings': 'My products',
          'tab3': 'Videos',
          'phone_number': 'Phone Number',
          'call': 'Call',
          'info_product': 'About the Product',
          'sold': 'For Sale',
          'most_popular_users': 'Most popular users',
          'filter': 'Filter',
          'category': 'Category',
          'count': 'Count',
          'save_avatar': 'Save Avatar',
          'choose_avatar': 'Choose Avatar',
          'name': 'Username',
          'change_profile': 'Change profile data',
          'brandingTitle': 'Atelyam: Show Your Style, Inspire Others!',
          'welcomeSubtitle': 'Please make sure to enter your username and phone number correctly.',
          'code_has_been_sent_to': 'Code has been sent to this number ',
          'verify': 'Verify',
          'verify_phone': 'Verify Phone number',
          'error': 'Error',
          'errorOTP': 'Please enter a valid OTP',
          'clear_all_favorites_desc': 'Are you sure you want to remove all products from your favorites?',
          'clear_all_favorites': 'Clear all favorites',
          'success': 'Success',
          'successClearedFavorites': 'All favorites have been cleared.',
          'choose_language': 'Choose Language',
          'noFavoritesFound': 'No items have been added to your favorites.',
          'successOTP': 'You logged in Successfully',
          'profile_change': 'Profile Change',
          'change_profile_success': 'User profile data changed successfully',
          'no_data_available': 'No data available',
          'no_category_image': 'No Image',
          'cancel': 'Cancel',
          'mostViewed': 'Most Viewed',
          'leastViewed': 'Least Viewed',
          'lastAdded': 'Newest photos',
          'firstAdded': 'Oldest photos',
          'mostViewedFasons': 'Most Viewed Fason',
          'add_product': 'Add product',
          'create_business_account': 'Create Business account',
          'create_product': 'Create product',
          'networkError': 'Network Error',
          'noInternet': 'No internet connection',
          'unknownError': 'Unknown Error',
          'anErrorOccurred': 'An error occurred',
          'apiError': 'API Error',
          'invalidNumber': 'Invalid Number',
          'unauthorized': 'Unauthorized',
          'notFound': 'Not Found',
          'userDoesNotExist': 'User does not exist, please register',
          'userExistsLogin': 'User exists please login',
          'serverError': 'Server Error',
          'errorStatus': 'Error Status',
          'last': 'Most Recent',
          'first': 'Earliest',
          'viewcount': 'Most Viewed',
          'LowPrice': 'Lowest Price',
          'HighPrice': 'Highest Price',
          'sold': 'Sold',
          'info_product': 'Product Information',
          'call': 'Call',
          'warning': 'Warning',
          'storage_permission_denied': 'Storage permission not granted. Download cannot be done.',
          'downloading': 'Downloading',
          'download_started': 'Download Started...',
          'success': 'Success',
          'downloaded': 'Image Downloaded and Added to Gallery.',
          'error': 'Error',
          'image_download_error': 'Error while downloading image: ',
          'phone_call_error': 'Could not launch',
          'call': 'Call',
          'tab1': 'Info',
          'tab2': 'Products',
          'tab3': 'Videos',
          'comingTitle': 'Coming Soon',
          'comingSubtitle': 'This section will be available soon, stay tuned for updates',
          'instagram': 'Instagram',
          'youtube': 'Youtube',
          'tiktok': 'TikTok',
          'phone_number': 'Phone Number',
          'location': 'Location',
          'url_error': 'Could not open URL',
          'url_error_message': 'I could not open the url you wanted to view',
          'productCount': 'product ',
          'business_accounts': 'Business accounts',
          'all_business_accounts': 'All Business Accounts',
          'new_product_upload': 'New Product Upload',
          'category': 'Category',
          'hashtag': 'Hashtag',
          'upload_image': 'Upload Image',
          'product_name': 'Product Name',
          'description': 'Description',
          'price': 'Price',
          'upload_product': 'Upload Product',
          'fill_all_fields': 'Please fill in all fields',
          'product_uploaded_success': 'Product uploaded successfully',
          'product_upload_failed': 'Product could not be uploaded:',
          'new_business_account': 'New Business Account',
          'business_name': 'Business Name',
          'phone': 'Phone',
          'address': 'Address',
          'logo_upload': 'Upload Logo',
          'account_created': 'Business account created successfully.',
          'account_already_exist': 'You already have a business account in this category.',
          'account_create_failed': 'Operation failed: ',
          'sending_information': 'Sending your information to the server, please wait...',
          'error': 'Error',
          'anErrorOccurred': 'An error occurred: ',
          'phone_call_error': 'Could not launch: ',
          'new_product_upload': 'New Product Upload',
          'category': 'Category',
          'hashtag': 'Hashtag',
          'upload_image': 'Upload Image',
          'product_name': 'Product Name',
          'description': 'Description',
          'price': 'Price',
          'upload_product': 'Upload Product',
          'fill_all_fields': 'Please fill in all fields',
          'product_uploaded_success': 'Product uploaded successfully',
          'product_upload_failed': 'Product could not be uploaded:',
          'new_business_account': 'New Business Account',
          'business_name': 'Business Name',
          'phone': 'Phone',
          'address': 'Address',
          'add_account': 'Add Account',
          'logo_upload': 'Upload Logo',
          'account_created': 'Business account created successfully.',
          'account_already_exist': 'You already have a business account in this category.',
          'account_create_failed': 'Operation failed: ',
          'sending_information': 'Sending your information to the server, please wait...',
          'error': 'Error',
          'anErrorOccurred': 'An error occurred: ',
          'phone_call_error': 'Could not launch: ',
          'update_business_account': 'Edit Business Account',
          'update_product': 'Update Product',
          'delete_product': 'Delete Product',
          'delete_account': 'Delete Account',
          'update': 'Update',
          'product_updated': 'Product updated successfully.',
          'product_not_updated': 'Product could not be updated:',
          'delete': 'Delete',
          'are_you_sure': 'Are you sure you want to delete this business account',
          'product': 'product',
          'cancel': 'Cancel',
          'business_account_updated': 'Account updated successfully',
          'business_account_not_updated': 'Update failed: ',
          'website': 'Website',
          'deleted_success': 'YOur business account deleted successfully',
          'wait': 'Please wait...',
          'wait_desc': 'Please wait while we process your request',
          'inactive': 'Inactive',
          'inactive_desc': 'Your account is inactive. Please contact support for more information.',
          'main_image_upload': 'Upload the product Main image',
          'upload_images': 'Upload other images',
          'update_product': 'Update Product',
          'update_image': 'Change Product Image',
          'product_updated': 'Product updated successfully',
          'update_failed': 'Update failed',
        },
        'tm': {},
        'tr': {},
        'ru': {},
        'ch': {},
      };
}
