// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'profil': 'Profile',
          'settings': 'Settings',
          'lang': 'Language',
          'aboutUs': 'About Us',
          'login': 'Login',
          'register': 'Register',
          'logout': 'Logout',
          'log_out_title': 'Do you want to really quit Our App?',
          'yes': 'Yes',
          'no': 'No',
          'logOutUser': 'You are logged out app successfully :(',
          'home': 'Home',
          'search': 'Search',
          'categories': 'Categories',
          'favorites': 'Favorites',
          'cart': 'Cart',
          'more': 'More',
          'dark': 'Dark',
          'light': 'Light',
          'en': 'English',
          'tm': 'Turkmen',
          'tr': 'Turkish',
          'ru': 'Russian',
          'ch': 'Chinese',
          'fashion': 'Fashion',
          'summer': 'Summer',
          'winter': 'Winter',
          'spring': 'Spring',
          'autumn': 'Autumn',
          'all': 'All',
          'new': 'New',
          'popular': 'Popular',
          'banners_profile': 'Banner Profile',
          'types_of_business': 'Types of Businesses',
          'commecial_users': 'Commercial Users',
          'location': 'Address',
          'comingTitle': 'Soon....',
          'comingSubtitle': 'This section will be available to our users very soon. We kindly ask for your patience.',
          'tab1': 'Information',
          'tab2': 'Products',
          'tab3': 'Videos',
          'phone_number': 'Phone Number',
          'call': 'Call',
          'info_product': 'About the Product',
          'sold': 'For Sale',
          'most_popular_users': 'Most popular users',
          'filter': 'Filter',
          'category': 'Category',
          'count': 'Count',
          'save_avatar': 'Save Avatar',
          'choose_avatar': 'Choose Avatar',
          'name': 'Username',
          'change_profile': 'Change profile data',
          'brandingTitle': 'Atelyam: Show Your Style, Inspire Others!',
          'welcomeSubtitle': 'Please make sure to enter your username and phone number correctly.',
          'code_has_been_sent_to': 'Code has been sent to this number ',
          'verify': 'Verify',
          'verify_phone': 'Verify Phone number',
          'error': 'Error',
          'errorOTP': 'Please enter a valid OTP',
          'clear_all_favorites_desc': 'Are you sure you want to remove all products from your favorites?',
          'clear_all_favorites': 'Clear all favorites',
          'success': 'Success',
          'successClearedFavorites': 'All favorites have been cleared.',
          'choose_language': 'Choose Language',
          'noFavoritesFound': 'No items have been added to your favorites.',
          'successOTP': 'You logged in Successfully',
          'profile_change': 'Profile Change',
          'change_profile_success': 'User profile data changed successfully',
          'no_data_available': 'No data available',
          'no_category_image': 'No Image',
          'cancel': 'Cancel',
          'mostViewed': 'Most Viewed',
          'leastViewed': 'Least Viewed',
          'lastAdded': 'Newest photos',
          'firstAdded': 'Oldest photos',
          'mostViewedFasons': 'Most Viewed Fason',
          'add_product': 'Add product',
          'create_business_account': 'Create Business account',
          'networkError': 'Network Error',
          'noInternet': 'No internet connection',
          'unknownError': 'Unknown Error',
          'anErrorOccurred': 'An error occurred',
          'apiError': 'API Error',
          'invalidNumber': 'Invalid Number',
          'unauthorized': 'Unauthorized',
          'notFound': 'Not Found',
          'userDoesNotExist': 'User does not exist, please register',
          'userExistsLogin': 'User exists please login',
          'serverError': 'Server Error',
          'errorStatus': 'Error Status',
        },
        'tm': {},
        'tr': {},
        'ru': {},
        'ch': {},
      };
}
